### ISSUE TITLE
More friendly colors

### ISSUE THREAD

**Issue by TobiGr** [FreeTubeApp/FreeTubeApp.io#9]
Hey,
the website has an easy and good structure, but somehow looks quite dark and thus not friendly to me. I'd suggest to use white text color more often. I don't have time to implement the changes, just edited with my browser's dev tools.
![Screenshot_2020-10-22 FreeTube - The Private YouTube Client](https://user-images.githubusercontent.com/17365767/96837344-8ebdc600-1446-11eb-8b4d-b4392a8c695a.jpg)

**Comment by PrestonN** [comment]
I was honestly thinking about doing this a while back, but I wasn't too sure about it.  After seeing the picture you provided, I think I like it this way.  I've gone ahead and made the change.  Hope that looks better :)

**Comment by TobiGr** [comment]
That was a quick response :)
I think, you can use
```CSS
.rounded-lg.bg-primary-accent.w-24.flex.justify-center {
    min-width: 6rem;
}
```
to enlarge the icon container to the same size.

And depending on the screen width, you could also change the margins of the corresponding descriptions.

``` CSS
.ml-12 {
    margin-left: 2.5rem;
    margin-right: 0.5rem;
}
```

![grafik](https://user-images.githubusercontent.com/17365767/96933646-2102b000-14c1-11eb-9412-3e39bc380d96.png)
